USE S_NAV;

-- NEEDS A BETTER SOLUTION BUT ONLY RUN ONCE

-- CAMPUS INSERTION
INSERT INTO CAMPUS VALUES ('TRAFALGAR'), ('DAVIS'), ('HMC');

-- TRAFALGAR WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('AA-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('AS-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('D-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('DAYCARE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('E-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('G-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('H-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('J-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('Elder Research Centre', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('ATHLETICS CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('S-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('STUDENT-CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));

-- DAVIS WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('DAYCARE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('H-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('J-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('M-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('M PORTABLES', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('STUDENT CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));

-- HMC WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));

-- FLOOR INSERTION (TRAF S-WING) (ARGUABLE IF IT SHOULD BE IN DATABASE OR ACCESSIBLE ON SERVER)
INSERT INTO FLOOR_LEVEL VALUES (1,
(SELECT * FROM OPENROWSET (BULK N'C:\Users\Jordan\Desktop\S-Nav\Database\Images\Traf\S-Wing\TRA-S-1.PNG', SINGLE_BLOB) AS FLOOR_PLAN),
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

INSERT INTO FLOOR_LEVEL VALUES (2,
(SELECT * FROM OPENROWSET (BULK N'C:\Users\Jordan\Desktop\S-Nav\Database\Images\Traf\S-Wing\TRA-S-2.PNG', SINGLE_BLOB) AS FLOOR_PLAN),
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

INSERT INTO FLOOR_LEVEL VALUES (3,
(SELECT * FROM OPENROWSET (BULK N'C:\Users\Jordan\Desktop\S-Nav\Database\Images\Traf\S-Wing\TRA-S-3.PNG', SINGLE_BLOB) AS FLOOR_PLAN),
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

INSERT INTO FLOOR_LEVEL VALUES (4,
(SELECT * FROM OPENROWSET (BULK N'C:\Users\Jordan\Desktop\S-Nav\Database\Images\Traf\S-Wing\TRA-S-4.PNG', SINGLE_BLOB) AS FLOOR_PLAN),
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));
SELECT * FROM FLOOR_LEVEL;
